/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/admin/AdminHeader.vue')['default']
    CardProduct: typeof import('./src/components/front/CardProduct.vue')['default']
    ContentContainer: typeof import('./src/components/front/ContentContainer.vue')['default']
    DefaultContainer: typeof import('./src/components/admin/DefaultContainer.vue')['default']
    DesktopCartTable: typeof import('./src/components/front/DesktopCartTable.vue')['default']
    DialogAdminArticle: typeof import('./src/components/admin/DialogAdminArticle.vue')['default']
    DialogAdminCoupon: typeof import('./src/components/admin/DialogAdminCoupon.vue')['default']
    DialogAdminOrder: typeof import('./src/components/admin/DialogAdminOrder.vue')['default']
    DialogAdminProduct: typeof import('./src/components/admin/DialogAdminProduct.vue')['default']
    DialogShowCoupon: typeof import('./src/components/front/DialogShowCoupon.vue')['default']
    DrawerCartList: typeof import('./src/components/front/DrawerCartList.vue')['default']
    DrawerProductCategory: typeof import('./src/components/front/DrawerProductCategory.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/front/Footer.vue')['default']
    Header: typeof import('./src/components/front/Header.vue')['default']
    MobileCartCard: typeof import('./src/components/front/MobileCartCard.vue')['default']
    QuestionAndAnswerForm: typeof import('./src/components/front/QuestionAndAnswerForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonCardProduct: typeof import('./src/components/front/SkeletonCardProduct.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
