export { default as DialogAdminProduct } from "./DialogAdminProduct.vue"
export { default as DialogAdminCoupon } from "./DialogAdminCoupon.vue"
export { default as DialogAdminOrder } from "./DialogAdminOrder.vue"
export { default as DialogAdminArticle } from "./DialogAdminArticle.vue"
export { default as DefaultContainer } from "./DefaultContainer.vue"